### ISSUE TITLE
@vue/cli webpack 4 integration

### ISSUE THREAD

**Issue by brandonpittman** [wix-playground/stylable-vue-example#1]
Vue CLI 3 already uses Webpack 4.

**Comment by idoros** [comment]
Thanks! We will check it out 👍

**Comment by brandonpittman** [comment]
No one cares about this.

**Comment by tomrav** [comment]
Thanks for bringing this issue back to light. Rest assured, we do care.

I'm sorry this hasn't gotten any further attention. It's a matter of resource allocation and priorities in the project, additionally we've gotten relatively little interest on this issue and so it never bumped up in the queue. If anyone in the Vue community would be able to pick it up, or help us understand the best way to integrate, that would be great.

I'll try to re-examine the issue, but can't promise anything further at the moment in terms of a time-table.

**Comment by brandonpittman** [comment]
It’s cool. I wasn’t trying to be mean or anything. Merry Christmas! 😊
